// content/services.ts
export const servicesContent = {
  headline: "Complete IT Solutions for Your Business",
  subheadline: "From stunning websites to complex business systems, we deliver technology solutions that work.",

  services: [
    {
      slug: "web-development",
      title: "Website Design & Development",
      shortDescription: "Professional websites that attract customers and drive business growth.",
      fullDescription: "We build stunning, high-performance websites that convert visitors into customers. Every site is custom-designed, SEO-optimized, and engineered for speed.",
      features: [
        "Custom responsive design",
        "SEO optimization",
        "E-commerce integration",
        "CMS for easy updates",
        "Analytics & tracking",
        "Fast hosting setup",
      ],
      benefits: [
        "Rank higher on Google",
        "Load in under 2 seconds",
        "Works on all devices",
        "Update content yourself",
      ],
      icon: "browser",
      category: "website" as const,
      featured: true,
      image: "https://placehold.co/800x600/B91C1C/white?text=Web+Development&font=roboto",
      detailPageUrl: "/services/web-development",
    },
    {
      slug: "custom-systems",
      title: "Custom Business Systems",
      shortDescription: "Tailored software solutions that streamline your operations and boost productivity.",
      fullDescription: "Stop forcing your business into generic software. We build custom systems designed around your unique workflows and requirements.",
      features: [
        "Attendance & HR systems",
        "Biometric integration",
        "Inventory management",
        "CRM solutions",
        "Custom dashboards",
        "Mobile applications",
      ],
      benefits: [
        "Eliminate manual processes",
        "Real-time business insights",
        "Secure data management",
        "Scalable architecture",
      ],
      icon: "dashboard",
      category: "systems" as const,
      featured: true,
      image: "https://placehold.co/800x600/000000/B91C1C?text=Business+Systems&font=roboto",
      detailPageUrl: "/services/custom-systems",
    },
    {
      slug: "digital-solutions",
      title: "Digital Invitations & Smart Cards",
      shortDescription: "Modern digital experiences for events, networking, and brand engagement.",
      fullDescription: "Impress your guests and clients with interactive digital invitations and smart business cards that make lasting impressions.",
      features: [
        "Custom event invitations",
        "Digital business cards (NFC)",
        "RSVP management",
        "QR code integration",
        "Guest analytics",
        "Social media sharing",
      ],
      benefits: [
        "Eco-friendly & cost-effective",
        "Track engagement in real-time",
        "Update details instantly",
        "Professional modern look",
      ],
      icon: "card",
      category: "digital" as const,
      featured: true,
      image: "https://placehold.co/800x600/B91C1C/white?text=Digital+Solutions&font=roboto",
      detailPageUrl: "/services/digital-solutions",
    },
    {
      slug: "video-production",
      title: "Video Production & Live Streaming",
      shortDescription: "Professional video content and live streaming for events, marketing, and training.",
      fullDescription: "From corporate videos to live event streaming, we deliver broadcast-quality production that engages your audience.",
      features: [
        "Corporate video production",
        "Live event streaming",
        "Multi-camera setups",
        "Professional editing",
        "YouTube/social optimization",
        "Hosting & distribution",
      ],
      benefits: [
        "Broadcast-quality output",
        "Reliable streaming",
        "Experienced crew",
        "Fast turnaround",
      ],
      icon: "video",
      category: "media" as const,
      featured: true,
      image: "https://placehold.co/800x600/000000/B91C1C?text=Video+Production&font=roboto",
      detailPageUrl: "/services/video-production",
    },
    {
      slug: "corporate-email",
      title: "Corporate Email Systems",
      shortDescription: "Professional email infrastructure that enhances your business credibility.",
      fullDescription: "Get professional email addresses with your domain name. Secure, reliable, and fully managed email systems.",
      features: [
        "Custom domain email",
        "Advanced spam protection",
        "Mobile & desktop sync",
        "Large attachment support",
        "Email migration services",
        "Team collaboration tools",
      ],
      benefits: [
        "Professional appearance",
        "99.9% uptime guarantee",
        "Enterprise security",
        "Easy setup & training",
      ],
      icon: "email",
      category: "infrastructure" as const,
      featured: true,
      image: "https://placehold.co/800x600/B91C1C/white?text=Corporate+Email&font=roboto",
      detailPageUrl: "/services/corporate-email",
    },
    {
      slug: "data-analysis",
      title: "Data Analysis & Business Intelligence",
      shortDescription: "Transform your data into actionable insights that drive smarter decisions.",
      fullDescription: "Stop drowning in spreadsheets. We build custom analytics dashboards that give you clear insights into your business performance.",
      features: [
        "Custom dashboards",
        "Automated reporting",
        "Data visualization",
        "Trend analysis",
        "Predictive analytics",
        "Database optimization",
      ],
      benefits: [
        "Make data-driven decisions",
        "Spot trends early",
        "Save hours on reporting",
        "Accessible to your team",
      ],
      icon: "chart",
      category: "systems" as const,
      featured: true,
      image: "https://placehold.co/800x600/000000/B91C1C?text=Data+Analysis&font=roboto",
      detailPageUrl: "/services/data-analysis",
    },
    {
      slug: "seo-digital-marketing",
      title: "SEO & Digital Marketing",
      shortDescription: "Get found online and attract more customers with strategic digital marketing.",
      fullDescription: "Rank higher on Google, reach more customers, and grow your online presence with our SEO and digital marketing services.",
      features: [
        "Search engine optimization",
        "Google Ads management",
        "Social media marketing",
        "Content strategy",
        "Email marketing campaigns",
        "Performance tracking",
      ],
      benefits: [
        "Increase website traffic",
        "Generate quality leads",
        "Improve online visibility",
        "Measurable ROI",
      ],
      icon: "megaphone",
      category: "digital" as const,
      featured: true,
      image: "https://placehold.co/800x600/B91C1C/white?text=SEO+Marketing&font=roboto",
      detailPageUrl: "/services/seo-digital-marketing",
    },
  ],

  categories: [
    { id: "all", label: "All Services" },
    { id: "website", label: "Web Solutions" },
    { id: "systems", label: "Business Systems" },
    { id: "infrastructure", label: "Infrastructure" },
    { id: "media", label: "Media Production" },
    { id: "digital", label: "Digital Solutions" },
  ],

  cta: {
    headline: "Not sure which service you need?",
    description: "Let's discuss your challenges and find the right solution together.",
    buttonText: "Get Free Consultation",
    buttonUrl: "#contact",
  },
} as const;