# Generated by Django 6.0.1 on 2026-02-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('service_name', models.CharField(default='Ricrene Investment Ltd', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('once', 'One-time')], default='monthly', max_length=10)),
                ('contact_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('form', 'Contact Form')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('mpesa_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mpesa_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Contact Inquiries'},
        ),
    ]
